# Generated by Django 4.1 on 2022-11-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
